version: "3.8"

name: "mariner"

services:
  luigi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luigi_scheduler
    ports:
      - "8082:8082"
    volumes:
      - ./container/output:/app/output
      - ./container/logs:/app/logs
